# Generated by Django 2.1 on 2019-05-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0003_auto_20190517_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rest_number',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
